version: "2"
services:
    mariadb:
        image: mariadb:10
        volumes:
            - data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=manager
            - MYSQL_PASSWORD=secret
        networks:
            - redDocker
    web:
        image: wordpress:6
        depends_on:
            - mariadb
        volumes:
            - ./target:/var/www/html
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_NAME=wordpress
        ports:
            - 82:80
        networks:
            - redDocker
networks:
  redDocker:

volumes:
    data:
